#!/usr/bin/env bash
set -euo pipefail
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

if [[ $1 == "ec2" ]]; then

    if [[ $2 == "describe-instance-types" ]]; then
        cat "${SCRIPTPATH}/m4-xlarge.json"
        exit 0
    fi

fi