---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Nvidia Builder Instance Profile'
Resources:
  NodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: EPAM-NVIDIA-BUILDER-READ-NVIDIA-DRIVERS-POLICY
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:Get*
            - s3:List*
            Resource:
            - "arn:aws:s3:::ec2-linux-nvidia-drivers"
            - "arn:aws:s3:::ec2-linux-nvidia-drivers/*"
      RoleName: epam-vae-nvidia-builder-role

  NodeInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles: 
      - !Ref NodeInstanceRole
      InstanceProfileName: epam-vae-nvidia-builder-profile

Outputs:
  NodeInstanceProfile:
    Value: !Ref NodeInstanceProfile
