version: '3.7'

services:
  packer:
    image: hashicorp/packer:1.2.4
    env_file:
      - .env
      - .vpc.env
    environment:
      - USER=lumoslabs
    working_dir: /build
    volumes:
      - .:/build
    dns:
      - 1.1.1.1
      - 1.0.0.1
networks:
  default:
    external:
      name: bridge
