site_name: Amazon EKS AMI
docs_dir: doc/
site_description: Build template and runtime resources for the Amazon EKS AMI
repo_name: awslabs/amazon-eks-ami
repo_url: https://github.com/awslabs/amazon-eks-ami
nav:
  - 'Overview': README.md
  - 'Changelog': CHANGELOG.md
  - 'Community':
    - 'Contribution guidelines': CONTRIBUTING.md
    - 'Code of Conduct': CODE_OF_CONDUCT.md
  - 'Development': development.md
  - 'Usage':
    - 'Overview': usage/overview.md
    - 'Amazon Linux 2': usage/al2.md
    - 'Amazon Linux 2023': usage/al2023.md
  - 'nodeadm':
    - 'Overview': nodeadm/README.md
    - 'API':
      - 'Concepts': nodeadm/doc/api-concepts.md
      - 'Reference': nodeadm/doc/api.md
    - 'Examples': nodeadm/doc/examples.md
    - 'Playground': nodeadm/doc/playground.md
theme:
  name: material
  palette:
    primary: black
  features:
    - navigation.sections
