name: "[Janitor] AMI sweeper"
description: "🗑️ Deletes CI AMI's when they're no longer needed"
inputs:
  max_age_seconds:
    description: "Number of seconds after creation when an AMI becomes eligible for deletion"
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/script.sh
      shell: bash
      env:
        MAX_AGE_SECONDS: ${{ inputs.max_age_seconds }}
