# version: 2.1

executors:
  packer:
    docker:
      - image: 411466821576.dkr.ecr.us-west-2.amazonaws.com/devops/ci/packer:1.11.0.release-release

jobs:
  prepare_env:
    executor: packer
    working_directory: ~/aws_ecr_ami
    steps:
      - checkout:
          path: ~/aws_ecr_ami
      - persist_to_workspace:
          root: "~"
          paths:
            - aws_ecr_ami

  build:
    executor: packer
    parameters:
      os_distro:
        type: string
      k8s_version:
        type: string
        default: "1.32"
    environment:
      K8S_VERSION: << parameters.k8s_version >>
      os_distro: << parameters.os_distro >>
    steps:
      - attach_workspace:
            at: .
      - run:
          name: Prepare BUILD_TAG env
          command: |
            NORMALIZED_BRANCH_NAME=$(echo ${CIRCLE_BRANCH} | sed 's/[^a-zA-Z0-9]/-/g' | cut -c 1-50)
            echo "export BUILD_TAG=${NORMALIZED_BRANCH_NAME}-${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1::7}" >> ${BASH_ENV}
            AMI_NAME="amazon-eks-node-${os_distro}-${K8S_VERSION}-$(date '+%Y-%m-%d')"
            echo "export AMI_NAME=${AMI_NAME}" >> ${BASH_ENV}
      - run:
          name: Install aws cli
          command: apk add aws-cli
      - run:
          name: Install dependency for packer
          command: cd aws_ecr_ami && packer plugins install github.com/hashicorp/amazon
      - run:
          name: Packer validate and build AMI
          no_output_timeout: 60m
          command: |
            cd aws_ecr_ami && PACKER_VARIABLE_FILE=fluence-eks-worker-${os_distro}-variables.json \
              make -e -j2 build os_distro=${os_distro} k8s=${K8S_VERSION}

workflows:
  aws_eks_ami:
    jobs:
      - prepare_env:
          context: AWS_OPERATIONS_DEV_0

      - build:
          name: build main al2
          os_distro: "al2"
          context:
            - AWS_OPERATIONS_0
            - PACKER_OPERATIONS_0
          requires:
            - prepare_env
          filters:
            branches:
              only:
                - merge_upstream_v20260818 #main

      - build:
          name: build main al2023
          os_distro: "al2023"
          context:
            - AWS_OPERATIONS_0
            - PACKER_OPERATIONS_0
          requires:
            - prepare_env
          filters:
            branches:
              only:
                - merge_upstream_v20260818 #main

      - build:
          name: build dev al2
          os_distro: "al2"
          context:
            - AWS_OPERATIONS_DEV_0
            - PACKER_OPERATIONS_DEV_0
          requires:
            - prepare_env
          filters:
            branches:
              only:
                - dev

      - build:
          name: build dev al2023
          os_distro: "al2023"
          context:
            - AWS_OPERATIONS_DEV_0
            - PACKER_OPERATIONS_DEV_0
          requires:
            - prepare_env
          filters:
            branches:
              only:
                - dev