#!/usr/bin/env bash

echo >&2 "mocking 'kubelet $*'"

# The only use of kubelet directly is to get the Kubernetes version,
# so we'll set a default here to avoid test failures, and you can
# override by setting the KUBELET_VERSION environment variable.
if [ $# == 1 ] && [ $1 == "--version" ]; then
  echo "Kubernetes ${KUBELET_VERSION:-v1.23.9-eks-ba74326}"
fi
