#!/usr/bin/env bash
# wrapper for shellcheck

set -o nounset

WORKDIR=$(realpath .)
FILES=$(hack/shfmt_command.sh --find --language-dialect auto "${WORKDIR}" | grep -v "nodeadm/vendor/")
SHELLCHECK_COMMAND=$(which shellcheck 2> /dev/null)
if [ -z "$SHELLCHECK_COMMAND" ]; then
  SHELLCHECK_COMMAND="docker run --rm -v $WORKDIR:$WORKDIR -w $WORKDIR koalaman/shellcheck:stable"
fi
$SHELLCHECK_COMMAND "$@" $FILES
