#!/bin/bash

if rpm -qa | grep -q kmod-nvidia; then
  echo -n "#############################################################
By using the EKS GPU Optimized AMI, you agree to the NVIDIA Cloud End User License Agreement
https://s3.amazonaws.com/EULA/NVidiaEULAforAWS.pdf.
#############################################################
"
fi
