ami_description                          = "EKS-optimized Kubernetes node based on Amazon Linux 2027"
ami_regions                              = ""
ami_users                                = ""
associate_public_ip_address              = ""
aws_region                               = "us-west-2"
binary_bucket_name                       = "amazon-eks"
binary_bucket_region                     = "us-west-2"
containerd_version                       = "2.*"
install_containerd_from_s3               = "false"
enable_efa                               = "true"
enable_fips                              = "false"
encrypted                                = "false"
iam_instance_profile                     = ""
kms_key_id                               = ""
launch_block_device_mappings_volume_size = "20"
nodeadm_build_image                      = "public.ecr.aws/eks-distro-build-tooling/golang:1.26"
pause_container_image                    = "public.ecr.aws/eks-distro/kubernetes/pause:3.10"
remote_folder                            = "/tmp"
runc_version                             = "*"
security_group_id                        = ""
source_ami_filter_name                   = "al2027-preview-ami-minimal-2027.*-kernel-7.1-*"
source_ami_id                            = ""
source_ami_owners                        = "137112412989"

# connect over SSM similarly to our internal build tooling
ssh_interface                         = "session_manager"

ssh_username                          = "ec2-user"
ssm_agent_version                     = ""
subnet_id                             = ""
temporary_security_group_source_cidrs = ""
volume_type                           = "gp3"
custom_endpoint_ec2                   = ""
