#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

# dkms may not be on the PATH. Discover the path from known paths
DKMS=""
for path in /usr/bin/dkms /usr/sbin/dkms; do
  if [ -x "$path" ]; then
    DKMS=$path
    break
  fi
done

DEPMOD=""
for path in /usr/bin/depmod /usr/sbin/depmod; do
  if [ -x "$path" ]; then
    DEPMOD=$path
    break
  fi
done


DKMS_ARCHIVE_DIR=/var/lib/dkms-archive

function log() {
  echo >&2 "$(date '+%Y-%m-%dT%H:%M:%S%z')" "[kmod-util]" "$@"
}

# get the version of a registered kernel module
function module-version() {
  ls /var/lib/dkms/${1}/ | head -n 1
}

# load a kernel module from the archives
function load() {
  local MODULE_NAME="${1}"
  local DISABLE_POST_TRANSACTION="${2:-false}"

  log "unpacking: ${MODULE_NAME}"
  local MODULE_ARCHIVE="${DKMS_ARCHIVE_DIR}/${MODULE_NAME}/*.tar.gz"
  if ${DKMS} ldtarball ${MODULE_ARCHIVE}; then
    log "unpacked tarball: ${MODULE_NAME}"
  else
    log "tarball already loaded, skipping unpack: ${MODULE_NAME}"
  fi
  log "installing: ${MODULE_NAME}"
  local MODULE_VERSION
  MODULE_VERSION=$(module-version "${MODULE_NAME}")

  if [[ "${DISABLE_POST_TRANSACTION}" == "true" ]]; then
    log "disabling dkms post_transaction"
    sudo mkdir -p /etc/dkms/framework.conf.d
    echo "post_transaction=" | sudo tee /etc/dkms/framework.conf.d/kmod-util.conf > /dev/null
  fi

  # dkms install returns exit code 0 when the module is already installed
  # handle this gracefully in case the behavior changes in a future version
  if ${DKMS} install -m "${MODULE_NAME}" -v "${MODULE_VERSION}" --no-depmod; then
    log "running depmod: ${MODULE_NAME}"
    ${DEPMOD} --quick
    log "finished depmod: ${MODULE_NAME}"
    log "installed: ${MODULE_NAME}"
  else
    log "module already installed, skipping: ${MODULE_NAME}"
  fi

  if [[ "${DISABLE_POST_TRANSACTION}" == "true" ]]; then
    log "re-enabling dkms post_transaction"
    sudo rm -f /etc/dkms/framework.conf.d/kmod-util.conf
  fi
}

# remove a kernel module
function remove() {
  local MODULE_NAME="${1}"
  log "removing: ${MODULE_NAME}"
  local MODULE_VERSION
  MODULE_VERSION=$(module-version "${MODULE_NAME}")
  ${DKMS} remove -m "${MODULE_NAME}" -v "${MODULE_VERSION}" --all
  log "removed: ${MODULE_NAME}"
}

# archive a kernel module
function archive() {
  local MODULE_NAME="${1}"
  log "archiving: ${MODULE_NAME}"
  mkdir -p "${DKMS_ARCHIVE_DIR}/${MODULE_NAME}"
  local MODULE_VERSION
  MODULE_VERSION=$(module-version "${MODULE_NAME}")
  ${DKMS} mktarball -m "${MODULE_NAME}" -v "${MODULE_VERSION}"
  cp /var/lib/dkms/${MODULE_NAME}/${MODULE_VERSION}/tarball/*.tar.gz "${DKMS_ARCHIVE_DIR}/${MODULE_NAME}/"
  log "archived: ${MODULE_NAME}"
}

# build a kernel module
function build() {
  local MODULE_NAME="${1}"
  local MODULE_VERSION
  MODULE_VERSION=$(module-version "${MODULE_NAME}")
  ${DKMS} build -m "${MODULE_NAME}" -v "${MODULE_VERSION}"
}

function usage() {
  echo >&2 "usage: $0 COMMAND MODULE_NAME"
  echo >&2
  echo >&2 "Valid values for COMMAND:"
  declare -F | awk '{print "\t" $3}' >&2
}

if [ "$#" -lt 2 ]; then
  usage
  exit 1
fi

"${@}"
