name: "Bot"
description: "🤖 beep boop"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1
    - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # 7.0.1
      with:
        script: |
          const crypto = require('crypto');
          const uuid = crypto.randomUUID();
          const bot = require('./.github/actions/bot/index.js');
          await bot(core, github, context, uuid);
