#!/usr/bin/env bash
set -euo pipefail

# The only use of kubelet directly is to get the Kubernetes version,
# so we'll set a default here to avoid test failures, and you can
# override by setting the KUBELET_VERSION environment variable.
some_kubelet_version="Kubernetes v1.20.15-eks-ba74326"
KUBELET_VERSION="${KUBELET_VERSION:-$some_kubelet_version}"
echo "$KUBELET_VERSION"
