//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapConfig) DeepCopyInto(out *BootstrapConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapConfig.
func (in *BootstrapConfig) DeepCopy() *BootstrapConfig {
	if in == nil {
		return nil
	}
	out := new(BootstrapConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BootstrapConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapConfigSpec) DeepCopyInto(out *BootstrapConfigSpec) {
	*out = *in
	out.ClusterDetails = in.ClusterDetails
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapConfigSpec.
func (in *BootstrapConfigSpec) DeepCopy() *BootstrapConfigSpec {
	if in == nil {
		return nil
	}
	out := new(BootstrapConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDetails) DeepCopyInto(out *ClusterDetails) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDetails.
func (in *ClusterDetails) DeepCopy() *ClusterDetails {
	if in == nil {
		return nil
	}
	out := new(ClusterDetails)
	in.DeepCopyInto(out)
	return out
}
