//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package bridge

import (
	v1alpha1 "github.com/awslabs/amazon-eks-ami/nodeadm/api/v1alpha1"
	api "github.com/awslabs/amazon-eks-ami/nodeadm/internal/api"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*v1alpha1.NodeConfig)(nil), (*api.NodeConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeConfig_To_api_NodeConfig(a.(*v1alpha1.NodeConfig), b.(*api.NodeConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*api.NodeConfig)(nil), (*v1alpha1.NodeConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_api_NodeConfig_To_v1alpha1_NodeConfig(a.(*api.NodeConfig), b.(*v1alpha1.NodeConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.NodeConfigList)(nil), (*api.NodeConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeConfigList_To_api_NodeConfigList(a.(*v1alpha1.NodeConfigList), b.(*api.NodeConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*api.NodeConfigList)(nil), (*v1alpha1.NodeConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_api_NodeConfigList_To_v1alpha1_NodeConfigList(a.(*api.NodeConfigList), b.(*v1alpha1.NodeConfigList), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_NodeConfig_To_api_NodeConfig(in *v1alpha1.NodeConfig, out *api.NodeConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	return nil
}

// Convert_v1alpha1_NodeConfig_To_api_NodeConfig is an autogenerated conversion function.
func Convert_v1alpha1_NodeConfig_To_api_NodeConfig(in *v1alpha1.NodeConfig, out *api.NodeConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeConfig_To_api_NodeConfig(in, out, s)
}

func autoConvert_api_NodeConfig_To_v1alpha1_NodeConfig(in *api.NodeConfig, out *v1alpha1.NodeConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	// INFO: in.Status opted out of conversion generation
	return nil
}

// Convert_api_NodeConfig_To_v1alpha1_NodeConfig is an autogenerated conversion function.
func Convert_api_NodeConfig_To_v1alpha1_NodeConfig(in *api.NodeConfig, out *v1alpha1.NodeConfig, s conversion.Scope) error {
	return autoConvert_api_NodeConfig_To_v1alpha1_NodeConfig(in, out, s)
}

func autoConvert_v1alpha1_NodeConfigList_To_api_NodeConfigList(in *v1alpha1.NodeConfigList, out *api.NodeConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]api.NodeConfig, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_NodeConfig_To_api_NodeConfig(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_NodeConfigList_To_api_NodeConfigList is an autogenerated conversion function.
func Convert_v1alpha1_NodeConfigList_To_api_NodeConfigList(in *v1alpha1.NodeConfigList, out *api.NodeConfigList, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeConfigList_To_api_NodeConfigList(in, out, s)
}

func autoConvert_api_NodeConfigList_To_v1alpha1_NodeConfigList(in *api.NodeConfigList, out *v1alpha1.NodeConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha1.NodeConfig, len(*in))
		for i := range *in {
			if err := Convert_api_NodeConfig_To_v1alpha1_NodeConfig(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_api_NodeConfigList_To_v1alpha1_NodeConfigList is an autogenerated conversion function.
func Convert_api_NodeConfigList_To_v1alpha1_NodeConfigList(in *api.NodeConfigList, out *v1alpha1.NodeConfigList, s conversion.Scope) error {
	return autoConvert_api_NodeConfigList_To_v1alpha1_NodeConfigList(in, out, s)
}
