---
name: "[ALAS] Open issues for new bulletins"
on:
  workflow_dispatch:
    inputs:
      window:
        description: "Only consider bulletins published within this relative time window (golang Duration)"
        default: "24h"
        required: true  
  schedule:
    # once an hour, at the top of hour
    - cron: "0 * * * *"
permissions:
  issues: write
jobs:
  alas-al2-bulletins:
    runs-on: ubuntu-latest
    steps:
      - uses: guilhem/rss-issues-action@0.5.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          feed: "https://alas.aws.amazon.com/AL2/alas.rss"
          dry-run: "true"
          lastTime: "${{ github.event.inputs.window || '24h' }}"
          labels: "alas,alas/al2"
          titleFilter: "(medium|low)"
