name: Bot
run-name: 🤖 beep boop
on:
  issue_comment:
    types:
      - created
jobs:
  bot:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
      - uses: ./.github/actions/bot
