name: "Default CI"
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
permissions:
  contents: read

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
    - run: make lint-docs
  lint-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
    - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    - run: make lint-code
