name: "Dependency Review"
on:
  pull_request:
    branches:
      - "main"
    paths:
      - '**.go'
permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0
      - uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # 5.0.0
  gosec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # 6.5.0
        with:
          go-version-file: 'nodeadm/go.mod'
      - run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - run: gosec -exclude-generated ./...
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0
      - uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # 1.0.4
        with:
          work-dir: ./nodeadm
          go-version-file: nodeadm/go.mod
          cache: false
          repo-checkout: false
