name: "Dependency Review"
on:
  pull_request:
    branches:
      - "main"
    paths:
      - '**.go'
permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0
      - uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # 5.0.0
  gosec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # 7.0.0
        with:
          go-version-file: 'nodeadm/go.mod'
      - run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - run: gosec -exclude-generated ./...
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0
      - uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f # 1.1.0
        with:
          work-dir: ./nodeadm
          go-version-file: nodeadm/go.mod
          cache: false
          repo-checkout: false
