name: 'Close stale issues'
on:
  schedule:
    # once a day at noon
    - cron: '0 12 * * *'
permissions:
  issues: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          days-before-stale: 90
          days-before-close: 14
          stale-issue-message: 'Please update this issue if it applies to the latest AMI release; otherwise it will be closed soon.'
          stale-issue-label: 'stale'
          exempt-issue-labels: 'never-stale'   
          # empty message will prevent PR's from being staled          
          stale-pr-message: ''
          debug-only: true