---
name: 'Update Dependencies'
on:
  workflow_dispatch:
  schedule:
    # every Monday
    - cron: '0 0 * * 1'
env:
  GOPROXY: https://proxy.golang.org
permissions:
  contents: read
jobs:
  update-deps:
    if: ${{ github.repository == 'awslabs/amazon-eks-ami' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # 4.2.1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_SYNC_ENI_MAX_PODS }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Update Nodeadm Doc References
        id: update_deps
        run: |
          cd nodeadm
          make update-doc-references
      - name: Create PR
        if: ${{ steps.update_deps.outputs.changes != '' }}
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # 7.0.8
        with:
          title: "chore(nodeadm): update doc references"
          commit-message: "chore(nodeadm): update doc references"
          committer: "GitHub <noreply@github.com>"
          author: "GitHub <noreply@github.com>"
          branch: update-doc-references
          base: main
          delete-branch: true
          labels: |
            changelog/exclude
          body: |
            Generated by:
            ```
            make update-doc-references
            ```
